# API KEYS
SHODAN_API_KEY = 'Q4wtGdNmqnaQ267zzUb2rQztDRayEISI'
IPINFO_API_KEY = '8d53c2357c2a13'

# DEFAULT WORDLISTS
PASSWORDS_WORDLIST = 'files/txt/passwords.txt'
SUBDOMAINS_WORDLIST = 'files/txt/subdomains.txt'